### ISSUE TITLE
Using Markdown or HTML in notifications?

### ISSUE THREAD

**Issue by emorell96** [notify-run/notify-run-server#6]
Hi,

Is it possible to use markdown or HTML in the notifications?

Thank you,

Enrique Morell

**Comment by paulgb** [comment]
Unfortunately, the [Notification API](https://notifications.spec.whatwg.org/) does not support anything except plain Unicode text.

If you just want bold and italic you could try using unicode fonts 𝗹𝗶𝗸𝗲 𝙩𝙝𝙞𝙨, but I'm not sure if all devices will render them right.
